apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ums-app
  template:
    metadata:
      labels:
        app: ums-app
    spec:
      containers:
        - name: ums-app
          image: steven8519/ums-app:0.0.7
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/umsdb
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: engineer25
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: ums-app
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
